[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retro_ab_av = { path = "../../retro_ab_av" }
retro_ab = { path = "../../retro_ab" }
retro_ab_gamepad = { path = "../" }
